### ISSUE TITLE
DXE-1923 EdgeWorker code upload to sandbox is not supported due to application/tar+gzip Content-Type

### ISSUE THREAD

**Issue by tomasz-krug-wttech** [akamai/AkamaiOPEN-edgegrid-node#125]
While uploading the EdgeWorker code the standard way through the `/edgeworkers/v1/ids/${edgeWorkerId}/versions` endpoint works fine it's impossible to do the same for the sandbox environment.

The sandbox endpoint I'm using is `/sandbox-api/v1/sandboxes/${sandboxId}/edgeworkers/${edgeWorkerId}` with the PUT method. [Link to official documentation](https://techdocs.akamai.com/sandbox/reference/put-sandbox-edgeworker).

The problem is that the sandbox endpoint requires the Content-Type header to have the value equal to `application/tar+gzip` while the standard one requires `application/gzip` and only the latter is supported in this library.

api.ts file. Line 61.
`let isTarball = req.body instanceof Uint8Array && req.headers['Content-Type'] === 'application/gzip';`

The goal is to recognize both `application/gzip` and `application/tar+gzip` content types as valid tarball options and handle the file buffer the same way in both cases.

**Comment by wzagrajcz** [comment]
Hello @tomasz-krug-wttech 
Thank You for opening that issue. We will work on that and go back to You in case of any uncertainties.

Thanks and best regards,
Wojciech

**Comment by majakubiec** [comment]
Hi @tomasz-krug-wttech,

We have fixed it already and it's waiting for release. We will inform you after its beed released.

BR

**Comment by lkowalsk-akamai-com** [comment]
Hi @tomasz-krug-wttech this issue should be resolved now. Please check and reopen ticket if needed.
