### ISSUE TITLE
[DXE-2050] garbled characters regarding axios recent version.

### ISSUE THREAD

**Issue by sena2112** [akamai/AkamaiOPEN-edgegrid-node#128]
API endpoint : /etp-report/v3/configs/*****/dns-activities/details
response code was 200 as well but the return body is garbed characters what I attached the example.

It is assumed that it could be possible to reproduce when the number of total character above 6,000 with edgegrid 3.3.0 ver.

We could see the published below, related aoxis previous version, is it related on this?
https://github.com/axios/axios/issues/5296
-->Had this issue, I set version to 1.1.x. Can confirm this fixed the issue, short term at least.

It's closed issue but looks like similar issue had before:
https://github.com/akamai/AkamaiOPEN-edgegrid-node/issues/83

**Comment by sena2112** [comment]
It is example part of response 
`{
    "status": 200,
    "statusText": "OK",
    "headers": {
        "server": "nginx",
        "content-type": "application/json",
        "x-ids-session-id": "49fc02df-bf71-401b-a1ec-1e0575be280f",
        "x-ratelimit-limit": "25",
        "vary": "accept-encoding",
        "x-trace-id": "a2136385cb67132c",
        "date": "Tue, 29 Nov 2022 09:05:49 GMT",
        "transfer-encoding": "chunked",
        "connection": "close, Transfer-Encoding"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "Blob": null
        },
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "Authorization": "EG1-HMAC-SHA256 client_token=;access_token=;timestamp=20221129T09:05:43+0000;nonce=18648b32-9a63-4993-9510-648ecf07faf7;signature=+eon4fh+5VU0cGaIrWNbMxkGJ4e0nqJPLIxBDBm2N7c=",
            "User-Agent": "axios/1.2.0",
            "Content-Length": "111",
            "Accept-Encoding": "gzip, deflate, br"
        },
        "path": "/etp-report/v3/configs/42360/dns-activities/details",
        "method": "post",
        "body": "{\"startTimeSec\":1669665257,\"endTimeSec\":1669708457,\"orderBy\":\"ASC\",\"pageNumber\":1,\"pageSize\":5000,\"filters\":{}}",
        "baseURL": "https://akab-eo4izmhcazyzgoo3-uugtoalgbocarjuy.luna.akamaiapis.net",
        "url": "https://akab-eo4izmhcazyzgoo3-uugtoalgbocarjuy.luna.akamaiapis.net/etp-report/v3/configs/42360/dns-activities/details",
        "maxRedirects": 0,
        "data": "{\"startTimeSec\":1669665257,\"endTimeSec\":1669708457,\"orderBy\":\"ASC\",\"pageNumber\":1,\"pageSize\":5000,\"filters\":{}}"
    },
    "request": {
        "_events": {},
        "_eventsCount": 3,
        "outputData": [],
        "outputSize": 0,
        "writable": true,
        "_last": true,
        "chunkedEncoding": false,
        "shouldKeepAlive": false,
        "_defaultKeepAlive": true,
        "useChunkedEncodingByDefault": true,
        "sendDate": false,
        "_removedConnection": false,
        "_removedContLen": false,
        "_removedTE": false,
        "_contentLength": 111,
        "_hasBody": true,
        "_trailer": "",
        "finished": true,
        "_headerSent": true,
        "socket": {
            "_tlsOptions": {
                "pipe": false,
                "secureContext": {
                    "context": {},
                    "singleUse": true
                },
                "isServer": false,
                "requestCert": true,
                "rejectUnauthorized": true,
                "session": {
                    "type": "Buffer",
                    "data": [48,130,8,134,2,1,1,2,2,3,3,4,2,192,48,4,32,204,113,124,146,49,4,93,144,13,37,216,183,159,101,57,65,84,125,179,185,222,240,23,246,84,9,252,254,43,9,100,90,4,48,98,182,3,215,183,204,114,218,232,195,47,88,217,184,194,128,169,149,222,172,170,179,24,32,195,200,109,40,133,221,216,253,185,191,153,102,159,204,141,198,126,213,53,229,94,74,215,21,161,6,2,4,99,133,203,93,162,4,2,2,28,32,163,130,6,230,48,130,6,226,48,130,5,202,160,3,2,1,2,2,16,9,245,2,194,19,72,113,199,194,130,244,147,210,83,173,204,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,48,79,49,11,48,9,6,3,85,4,6,19,2,85,83,49,21,48,19,6,3,85,4,10,19,12,68,105,103,105,67,101,114,116,32,73,110,99,49,41,48,39,6,3,85,4,3,19,32,68,105,103,105,67,101,114,116,32,84,76,83,32,82,83,65,32,83,72,65,50,53,54,32,50,48,50,48,32,67,65,49,48,30,23,13,50,50,48,54,50,51,48,48,48,48,48,48,90,23,13,50,51,48,54,50,51,50,51,53,57,53,57,90,48,124,49,11,48,9,6,3,85,4,6,19,2,85,83,49,22,48,20,6,3,85,4,8,19,13,77,97,115,115,97,99,104,117,115,101,116,116,115,49,18,48,16,6,3,85,4,7,19,9,67,97,109,98,114,105,100,103,101,49,33,48,31,6,3,85,4,10,19,24,65,107,97,109,97,105,32,84,101,99,104,110,111,108,111,103,105,101,115,44,32,73,110,99,49,30,48,28,6,3,85,4,3,12,21,42,46,108,117,110,97,46,97,107,97,109,97,105,97,112,105,115,46,110,101,116,48,130,1,34,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,3,130,1,15,0,48,130,1,10,2,130,1,1,0,242,95,49,179,54,22,5,225,31,126,127,148,58,246,84,170,7,99,61,79,154,163,78,1,106,27,63,151,216,76,234,133,22,117,46,153,2,210,11,162,165,234,167,169,197,48,21,187,68,176,251,150,60,195,235,68,30,206,133,168,207,188,139,48,143,73,13,45,120,67,214,82,144,229,97,162,112,142,54,33,170,36,129,74,84,156,215,242,188,244,236,217,103,124,169,103,9,240,251,210,112,106,250,138,92,172,194,124,63,78,151,60,255,168,8,244,254,223,238,203,131,201,53,90,190,213,140,29,59,42,45,150,163,115,77,104,83,22,40,221,207,145,211,148,98,245,31,133,93,176,185,205,246,157,243,93,158,113,38,183,126,81,188,163,151,243,163,139,23,231,106,183,93,0,130,101,130,154,27,230,8,127,166,37,87,169,5,50,112,249,14,174,176,90,12,222,91,36,72,75,39,127,34,115,59,190,253,233,63,183,70,69,128,32,141,85,44,148,27,8,203,61,142,223,151,36,158,29,152,225,204,73,1,225,242,214,28,120,167,246,102,214,124,87,87,136,243,107,193,213,39,83,14,2,222,233,2,3,1,0,1,163,130,3,139,48,130,3,135,48,31,6,3,85,29,35,4,24,48,22,128,20,183,107,162,234,168,170,132,140,121,234,180,218,15,152,178,197,149,118,185,244,48,29,6,3,85,29,14,4,22,4,20,68,72,92,127,249,98,110,208,64,152,28,35,28,123,121,66,183,177,181,51,48,53,6,3,85,29,17,4,46,48,44,130,21,42,46,108,117,110,97,46,97,107,97,109,97,105,97,112,105,115,46,110,101,116,130,19,108,117,110,97,46,97,107,97,109,97,105,97,112,105,115,46,110,101,116,48,14,6,3,85,29,15,1,1,255,4,4,3,2,5,160,48,29,6,3,85,29,37,4,22,48,20,6,8,43,6,1,5,5,7,3,1,6,8,43,6,1,5,5,7,3,2,48,129,143,6,3,85,29,31,4,129,135,48,129,132,48,64,160,62,160,60,134,58,104,116,116,112,58,47,47,99,114,108,51,46,100,105,103,105,99,101,114,116,46,99,111,109,47,68,105,103,105,67,101,114,116,84,76,83,82,83,65,83,72,65,50,53,54,50,48,50,48,67,65,49,45,52,46,99,114,108,48,64,160,62,160,60,134,58,104,116,116,112,58,47,47,99,114,108,52,46,100,105,103,105,99,101,114,116,46,99,111,109,47,68,105,103,105,67,101,114,116,84,76,83,82,83,65,83,72,65,50,53,54,50,48,50,48,67,65,49,45,52,46,99,114,108,48,62,6,3,85,29,32,4,55,48,53,48,51,6,6,103,129,12,1,2,2,48,41,48,39,6,8,43,6,1,5,5,7,2,1,22,27,104,116,116,112,58,47,47,119,119,119,46,100,105,103,105,99,101,114,116,46,99,111,109,47,67,80,83,48,127,6,8,43,6,1,5,5,7,1,1,4,115,48,113,48,36,6,8,43,6,1,5,5,7,48,1,134,24,104,116,116,112,58,47,47,111,99,115,112,46,100,105,103,105,99,101,114,116,46,99,111,109,48,73,6,8,43,6,1,5,5,7,48,2,134,61,104,116,116,112,58,47,47,99,97,99,101,114,116,115,46,100,105,103,105,99,101,114,116,46,99,111,109,47,68,105,103,105,67,101,114,116,84,76,83,82,83,65,83,72,65,50,53,54,50,48,50,48,67,65,49,45,49,46,99,114,116,48,9,6,3,85,29,19,4,2,48,0,48,130,1,127,6,10,43,6,1,4,1,214,121,2,4,2,4,130,1,111,4,130,1,107,1,105,0,118,0,232,62,208,218,62,245,6,53,50,231,87,40,188,137,107,201,3,211,203,209,17,107,236,235,105,225,119,125,109,6,189,110,0,0,1,129,146,107,66,210,0,0,4,3,0,71,48,69,2,32,69,148,255,157,220,137,7,0,240,31,205,104,100,53,226,243,29,64,199,252,111,121,253,136,255,184,34,85,185,133,159,232,2,33,0,242,227,5,22,251,13,29,12,111,193,120,12,154,71,67,151,61,179,246,143,148,105,183,72,110,119,142,4,43,222,134,78,0,119,0,53,207,25,27,191,177,108,87,191,15,173,76,109,66,203,187,182,39,32,38,81,234,63,225,42,239,168,3,195,59,214,76,0,0,1,129,146,107,67,19,0,0,4,3,0,72,48,70,2,33,0,148,106,17,134,237,169,38,112,175,172,91,217,27,102,188,21,19,122,22,185,166,68,206,197,226,170,190,198,205,69,3,230,2,33,0,245,19,220,120,94,1,228,38,92,46,85,171,146,185,49,10,123,16,203,160,11,91,236,192,92,182,100,141,192,66,193,230,0,118,0,183,62,251,36,223,156,77,186,117,242,57,197,186,88,244,108,93,252,66,207,122,159,53,196,158,29,9,129,37,237,180,153,0,0,1,129,146,107,66,230,0,0,4,3,0,71,48,69,2,32,72,163,174,188,240,7,226,88,223,128,67,19,56,166,67,167,123,185,216,133,239,150,210,201,33,49,7,187,64,120,34,40,2,33,0,148,26,25,151,164,123,89,53,227,139,113,91,112,122,149,71,106,114,233,87,154,40,136,167,205,95,152,107,50,170,230,12,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,3,130,1,1,0,99,122,194,159,116,83,198,11,48,177,201,97,149,26,54,255,150,0,91,95,48,253,229,231,143,242,252,251,254,12,148,3,156,220,243,189,1,204,87,228,5,137,190,15,207,102,39,135,39,48,11,232,159,94,166,54,245,113,42,37,53,33,71,64,155,111,188,159,24,46,254,179,84,192,177,205,92,100,53,15,60,36,193,232,5,16,91,153,143,69,63,49,25,71,196,229,9,86,72,157,251,206,203,255,208,0,244,203,28,187,12,222,12,170,223,94,88,236,21,67,14,193,215,152,164,225,191,63,217,240,1,33,171,146,226,78,158,206,58,123,77,253,254,56,185,46,42,153,73,203,198,208,176,115,209,7,41,50,43,169,59,12,176,84,244,158,30,205,78,20,75,24,89,176,48,104,87,161,139,244,249,206,127,116,213,52,107,237,223,172,153,206,123,202,196,174,19,43,234,146,30,137,45,140,26,250,163,247,142,30,188,7,133,179,141,192,215,7,208,154,217,124,167,219,160,62,245,59,182,225,92,232,178,26,248,91,200,206,167,193,160,225,64,78,97,112,217,203,188,51,214,252,57,198,213,122,164,2,4,0,166,60,4,58,97,107,97,98,45,101,111,52,105,122,109,104,99,97,122,121,122,103,111,111,51,45,117,117,103,116,111,97,108,103,98,111,99,97,114,106,117,121,46,108,117,110,97,46,97,107,97,109,97,105,97,112,105,115,46,110,101,116,169,5,2,3,1,68,156,170,129,227,4,129,224,0,0,31,63,247,244,196,18,151,43,163,161,134,80,240,199,142,17,189,70,25,47,133,130,222,73,122,189,122,16,33,82,49,46,10,125,168,1,100,15,236,134,129,81,51,130,163,174,35,235,182,211,244,130,222,150,245,254,56,66,58,211,68,242,200,162,182,57,175,98,215,164,124,70,247,38,177,144,37,40,36,166,221,206,159,29,221,229,155,49,225,25,69,156,29,110,85,75,5,49,26,232,5,72,205,251,178,242,40,237,249,112,6,33,108,202,221,12,231,220,91,118,120,117,201,127,194,12,179,57,156,223,123,44,163,4,85,138,91,211,51,13,41,108,133,191,98,25,34,212,183,203,253,156,90,54,116,133,23,78,226,11,63,164,95,232,235,146,56,189,17,246,128,162,163,61,155,14,71,5,115,72,8,198,110,122,204,99,82,130,185,211,167,96,153,233,205,127,177,229,232,49,4,14,5,72,191,115,41,123,200,38,130,139,68,102,246,153,142,115,222,238,198,29]
                }
            },
            "_secureEstablished": true,
            "_securePending": false,
            "_newSessionPending": false,
            "_controlReleased": true,
            "secureConnecting": false,
            "_SNICallback": null,
            "servername": "akab-eo4izmhcazyzgoo3-uugtoalgbocarjuy.luna.akamaiapis.net",
            "alpnProtocol": false,
            "authorized": true,
            "authorizationError": null,
            "encrypted": true,
            "_events": {
                "close": [
                    null,
                    null,
                    null,
                    null
                ]
            },
            "_eventsCount": 10,
            "connecting": false,
            "_hadError": false,
            "_parent": null,
            "_host": "akab-eo4izmhcazyzgoo3-uugtoalgbocarjuy.luna.akamaiapis.net",
            "_readableState": {
                "objectMode": false,
                "highWaterMark": 16384,
                "buffer": {
                    "head": null,
                    "tail": null,
                    "length": 0
                },
                "length": 0,
                "pipes": null,
                "pipesCount": 0,
                "flowing": true,
                "ended": false,
                "endEmitted": false,
                "reading": true,
                "sync": false,
                "needReadable": true,
                "emittedReadable": false,
                "readableListening": false,
                "resumeScheduled": false,
                "emitClose": false,
                "autoDestroy": false,
                "destroyed": false,
                "defaultEncoding": "utf8",
                "awaitDrainWriters": null,
                "multiAwaitDrain": false,
                "readingMore": false,
                "decoder": null,
                "encoding": null
            },
            "readable": true,
            "_writableState": {
                "objectMode": false,
                "highWaterMark": 16384,
                "finalCalled": true,
                "needDrain": false,
                "ending": true,
                "ended": true,
                "finished": false,
                "destroyed": false,
                "decodeStrings": false,
                "defaultEncoding": "utf8",
                "length": 0,
                "writing": false,
                "corked": 0,
                "sync": false,
                "bufferProcessing": false,
                "writecb": null,
                "writelen": 0,
                "afterWriteTickInfo": null,
                "bufferedRequest": null,
                "lastBufferedRequest": null,
                "pendingcb": 1,
                "prefinished": false,
                "errorEmitted": false,
                "emitClose": false,
                "autoDestroy": false,
                "bufferedRequestCount": 0,
                "corkedRequestsFree": {
                    "next": {
                        "next": null,
                        "entry": null
                    },
                    "entry": null
                }
            },
            "writable": false,
            "allowHalfOpen": false,
            "_sockname": null,
            "_pendingData": null,
            "_pendingEncoding": "",
            "_server": null,
            "ssl": {
                "_parent": {
                    "reading": true,
                    "onconnection": null
                },
                "reading": true
            },
            "_requestCert": true,
            "_rejectUnauthorized": true,
            "parser": null
        },
        "_header": "POST /etp-report/v3/configs/42360/dns-activities/details HTTP/1.1rnAccept: application/json, text/plain, */*rnContent-Type: application/jsonrnAuthorization: EG1-HMAC-SHA256 client_token=;access_token=;timestamp=20221129T09:05:43+0000;nonce=18648b32-9a63-4993-9510-648ecf07faf7;signature=+eon4fh+5VU0cGaIrWNbMxkGJ4e0nqJPLIxBDBm2N7c=rnUser-Agent: axios/1.2.0rnContent-Length: 111rnAccept-Encoding: gzip, deflate, brrnHost: akab-eo4izmhcazyzgoo3-uugtoalgbocarjuy.luna.akamaiapis.netrnConnection: closernrn",
        "_keepAliveTimeout": 0,
        "agent": {
            "_events": {},
            "_eventsCount": 2,
            "defaultPort": 443,
            "protocol": "https:",
            "options": {
                "path": null
            },
            "requests": {},
            "sockets": {
                "akab-eo4izmhcazyzgoo3-uugtoalgbocarjuy.luna.akamaiapis.net:443::::::::::::::::::": [
                    null
                ]
            },
            "freeSockets": {},
            "keepAliveMsecs": 1000,
            "keepAlive": false,
            "maxSockets": null,
            "maxFreeSockets": 256,
            "maxTotalSockets": null,
            "totalSocketCount": 1,
            "scheduling": "fifo",
            "maxCachedSessions": 100,
            "_sessionCache": {
                "map": {
                    "akab-eo4izmhcazyzgoo3-uugtoalgbocarjuy.luna.akamaiapis.net:443::::::::::::::::::": {
                        "type": "Buffer",
                        "data": [48,130,8,134,2,1,1,2,2,3,3,4,2,192,48,4,32,204,113,124,146,49,4,93,144,13,37,216,183,159,101,57,65,84,125,179,185,222,240,23,246,84,9,252,254,43,9,100,90,4,48,98,182,3,215,183,204,114,218,232,195,47,88,217,184,194,128,169,149,222,172,170,179,24,32,195,200,109,40,133,221,216,253,185,191,153,102,159,204,141,198,126,213,53,229,94,74,215,21,161,6,2,4,99,133,203,93,162,4,2,2,28,32,163,130,6,230,48,130,6,226,48,130,5,202,160,3,2,1,2,2,16,9,245,2,194,19,72,113,199,194,130,244,147,210,83,173,204,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,48,79,49,11,48,9,6,3,85,4,6,19,2,85,83,49,21,48,19,6,3,85,4,10,19,12,68,105,103,105,67,101,114,116,32,73,110,99,49,41,48,39,6,3,85,4,3,19,32,68,105,103,105,67,101,114,116,32,84,76,83,32,82,83,65,32,83,72,65,50,53,54,32,50,48,50,48,32,67,65,49,48,30,23,13,50,50,48,54,50,51,48,48,48,48,48,48,90,23,13,50,51,48,54,50,51,50,51,53,57,53,57,90,48,124,49,11,48,9,6,3,85,4,6,19,2,85,83,49,22,48,20,6,3,85,4,8,19,13,77,97,115,115,97,99,104,117,115,101,116,116,115,49,18,48,16,6,3,85,4,7,19,9,67,97,109,98,114,105,100,103,101,49,33,48,31,6,3,85,4,10,19,24,65,107,97,109,97,105,32,84,101,99,104,110,111,108,111,103,105,101,115,44,32,73,110,99,49,30,48,28,6,3,85,4,3,12,21,42,46,108,117,110,97,46,97,107,97,109,97,105,97,112,105,115,46,110,101,116,48,130,1,34,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,3,130,1,15,0,48,130,1,10,2,130,1,1,0,242,95,49,179,54,22,5,225,31,126,127,148,58,246,84,170,7,99,61,79,154,163,78,1,106,27,63,151,216,76,234,133,22,117,46,153,2,210,11,162,165,234,167,169,197,48,21,187,68,176,251,150,60,195,235,68,30,206,133,168,207,188,139,48,143,73,13,45,120,67,214,82,144,229,97,162,112,142,54,33,170,36,129,74,84,156,215,242,188,244,236,217,103,124,169,103,9,240,251,210,112,106,250,138,92,172,194,124,63,78,151,60,255,168,8,244,254,223,238,203,131,201,53,90,190,213,140,29,59,42,45,150,163,115,77,104,83,22,40,221,207,145,211,148,98,245,31,133,93,176,185,205,246,157,243,93,158,113,38,183,126,81,188,163,151,243,163,139,23,231,106,183,93,0,130,101,130,154,27,230,8,127,166,37,87,169,5,50,112,249,14,174,176,90,12,222,91,36,72,75,39,127,34,115,59,190,253,233,63,183,70,69,128,32,141,85,44,148,27,8,203,61,142,223,151,36,158,29,152,225,204,73,1,225,242,214,28,120,167,246,102,214,124,87,87,136,243,107,193,213,39,83,14,2,222,233,2,3,1,0,1,163,130,3,139,48,130,3,135,48,31,6,3,85,29,35,4,24,48,22,128,20,183,107,162,234,168,170,132,140,121,234,180,218,15,152,178,197,149,118,185,244,48,29,6,3,85,29,14,4,22,4,20,68,72,92,127,249,98,110,208,64,152,28,35,28,123,121,66,183,177,181,51,48,53,6,3,85,29,17,4,46,48,44,130,21,42,46,108,117,110,97,46,97,107,97,109,97,105,97,112,105,115,46,110,101,116,130,19,108,117,110,97,46,97,107,97,109,97,105,97,112,105,115,46,110,101,116,48,14,6,3,85,29,15,1,1,255,4,4,3,2,5,160,48,29,6,3,85,29,37,4,22,48,20,6,8,43,6,1,5,5,7,3,1,6,8,43,6,1,5,5,7,3,2,48,129,143,6,3,85,29,31,4,129,135,48,129,132,48,64,160,62,160,60,134,58,104,116,116,112,58,47,47,99,114,108,51,46,100,105,103,105,99,101,114,116,46,99,111,109,47,68,105,103,105,67,101,114,116,84,76,83,82,83,65,83,72,65,50,53,54,50,48,50,48,67,65,49,45,52,46,99,114,108,48,64,160,62,160,60,134,58,104,116,116,112,58,47,47,99,114,108,52,46,100,105,103,105,99,101,114,116,46,99,111,109,47,68,105,103,105,67,101,114,116,84,76,83,82,83,65,83,72,65,50,53,54,50,48,50,48,67,65,49,45,52,46,99,114,108,48,62,6,3,85,29,32,4,55,48,53,48,51,6,6,103,129,12,1,2,2,48,41,48,39,6,8,43,6,1,5,5,7,2,1,22,27,104,116,116,112,58,47,47,119,119,119,46,100,105,103,105,99,101,114,116,46,99,111,109,47,67,80,83,48,127,6,8,43,6,1,5,5,7,1,1,4,115,48,113,48,36,6,8,43,6,1,5,5,7,48,1,134,24,104,116,116,112,58,47,47,111,99,115,112,46,100,105,103,105,99,101,114,116,46,99,111,109,48,73,6,8,43,6,1,5,5,7,48,2,134,61,104,116,116,112,58,47,47,99,97,99,101,114,116,115,46,100,105,103,105,99,101,114,116,46,99,111,109,47,68,105,103,105,67,101,114,116,84,76,83,82,83,65,83,72,65,50,53,54,50,48,50,48,67,65,49,45,49,46,99,114,116,48,9,6,3,85,29,19,4,2,48,0,48,130,1,127,6,10,43,6,1,4,1,214,121,2,4,2,4,130,1,111,4,130,1,107,1,105,0,118,0,232,62,208,218,62,245,6,53,50,231,87,40,188,137,107,201,3,211,203,209,17,107,236,235,105,225,119,125,109,6,189,110,0,0,1,129,146,107,66,210,0,0,4,3,0,71,48,69,2,32,69,148,255,157,220,137,7,0,240,31,205,104,100,53,226,243,29,64,199,252,111,121,253,136,255,184,34,85,185,133,159,232,2,33,0,242,227,5,22,251,13,29,12,111,193,120,12,154,71,67,151,61,179,246,143,148,105,183,72,110,119,142,4,43,222,134,78,0,119,0,53,207,25,27,191,177,108,87,191,15,173,76,109,66,203,187,182,39,32,38,81,234,63,225,42,239,168,3,195,59,214,76,0,0,1,129,146,107,67,19,0,0,4,3,0,72,48,70,2,33,0,148,106,17,134,237,169,38,112,175,172,91,217,27,102,188,21,19,122,22,185,166,68,206,197,226,170,190,198,205,69,3,230,2,33,0,245,19,220,120,94,1,228,38,92,46,85,171,146,185,49,10,123,16,203,160,11,91,236,192,92,182,100,141,192,66,193,230,0,118,0,183,62,251,36,223,156,77,186,117,242,57,197,186,88,244,108,93,252,66,207,122,159,53,196,158,29,9,129,37,237,180,153,0,0,1,129,146,107,66,230,0,0,4,3,0,71,48,69,2,32,72,163,174,188,240,7,226,88,223,128,67,19,56,166,67,167,123,185,216,133,239,150,210,201,33,49,7,187,64,120,34,40,2,33,0,148,26,25,151,164,123,89,53,227,139,113,91,112,122,149,71,106,114,233,87,154,40,136,167,205,95,152,107,50,170,230,12,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,3,130,1,1,0,99,122,194,159,116,83,198,11,48,177,201,97,149,26,54,255,150,0,91,95,48,253,229,231,143,242,252,251,254,12,148,3,156,220,243,189,1,204,87,228,5,137,190,15,207,102,39,135,39,48,11,232,159,94,166,54,245,113,42,37,53,33,71,64,155,111,188,159,24,46,254,179,84,192,177,205,92,100,53,15,60,36,193,232,5,16,91,153,143,69,63,49,25,71,196,229,9,86,72,157,251,206,203,255,208,0,244,203,28,187,12,222,12,170,223,94,88,236,21,67,14,193,215,152,164,225,191,63,217,240,1,33,171,146,226,78,158,206,58,123,77,253,254,56,185,46,42,153,73,203,198,208,176,115,209,7,41,50,43,169,59,12,176,84,244,158,30,205,78,20,75,24,89,176,48,104,87,161,139,244,249,206,127,116,213,52,107,237,223,172,153,206,123,202,196,174,19,43,234,146,30,137,45,140,26,250,163,247,142,30,188,7,133,179,141,192,215,7,208,154,217,124,167,219,160,62,245,59,182,225,92,232,178,26,248,91,200,206,167,193,160,225,64,78,97,112,217,203,188,51,214,252,57,198,213,122,164,2,4,0,166,60,4,58,97,107,97,98,45,101,111,52,105,122,109,104,99,97,122,121,122,103,111,111,51,45,117,117,103,116,111,97,108,103,98,111,99,97,114,106,117,121,46,108,117,110,97,46,97,107,97,109,97,105,97,112,105,115,46,110,101,116,169,5,2,3,1,68,156,170,129,227,4,129,224,0,0,31,63,247,244,196,18,151,43,163,161,134,80,240,199,142,17,189,70,25,47,133,130,222,73,122,189,122,16,33,82,49,46,10,125,168,1,100,15,236,134,129,81,51,130,163,174,35,235,182,211,244,130,222,150,245,254,56,66,58,211,68,242,200,162,182,57,175,98,215,164,124,70,247,38,177,144,37,40,36,166,221,206,159,29,221,229,155,49,225,25,69,156,29,110,85,75,5,49,26,232,5,72,205,251,178,242,40,237,249,112,6,33,108,202,221,12,231,220,91,118,120,117,201,127,194,12,179,57,156,223,123,44,163,4,85,138,91,211,51,13,41,108,133,191,98,25,34,212,183,203,253,156,90,54,116,133,23,78,226,11,63,164,95,232,235,146,56,189,17,246,128,162,163,61,155,14,71,5,115,72,8,198,110,122,204,99,82,130,185,211,167,96,153,233,205,127,177,229,232,49,4,14,5,72,191,115,41,123,200,38,130,139,68,102,246,153,142,115,222,238,198,29]
                    }
                },
                "list": [
                    "akab-eo4izmhcazyzgoo3-uugtoalgbocarjuy.luna.akamaiapis.net:443::::::::::::::::::"
                ]
            }
        },
        "method": "POST",
        "path": "/etp-report/v3/configs/42360/dns-activities/details",
        "_ended": true,
        "res": {
            "_readableState": {
                "objectMode": false,
                "highWaterMark": 16384,
                "buffer": {
                    "head": null,
                    "tail": null,
                    "length": 0
                },
                "length": 0,
                "pipes": null,
                "pipesCount": 0,
                "flowing": true,
                "ended": true,
                "endEmitted": true,
                "reading": false,
                "sync": false,
                "needReadable": false,
                "emittedReadable": false,
                "readableListening": false,
                "resumeScheduled": false,
                "emitClose": true,
                "autoDestroy": false,
                "destroyed": false,
                "defaultEncoding": "utf8",
                "awaitDrainWriters": null,
                "multiAwaitDrain": false,
                "readingMore": false,
                "decoder": null,
                "encoding": null
            },
            "readable": false,
            "_events": {
                "end": [
                    null,
                    null
                ]
            },
            "_eventsCount": 4,
            "httpVersionMajor": 1,
            "httpVersionMinor": 1,
            "httpVersion": "1.1",
            "complete": true,
            "headers": {
                "server": "nginx",
                "content-type": "application/json",
                "x-ids-session-id": "49fc02df-bf71-401b-a1ec-1e0575be280f",
                "x-ratelimit-limit": "25",
                "vary": "accept-encoding",
                "x-trace-id": "a2136385cb67132c",
                "date": "Tue, 29 Nov 2022 09:05:49 GMT",
                "transfer-encoding": "chunked",
                "connection": "close, Transfer-Encoding"
            },
            "rawHeaders": [
                "Server",
                "nginx",
                "Content-Type",
                "application/json",
                "x-ids-session-id",
                "49fc02df-bf71-401b-a1ec-1e0575be280f",
                "X-RateLimit-Limit",
                "25",
                "Vary",
                "accept-encoding",
                "Content-Encoding",
                "gzip",
                "x-trace-id",
                "a2136385cb67132c",
                "Date",
                "Tue, 29 Nov 2022 09:05:49 GMT",
                "Transfer-Encoding",
                "chunked",
                "Connection",
                "close",
                "Connection",
                "Transfer-Encoding"
            ],
            "trailers": {},
            "rawTrailers": [],
            "aborted": false,
            "upgrade": false,
            "url": "",
            "method": null,
            "statusCode": 200,
            "statusMessage": "OK",
            "_consuming": true,
            "_dumped": false
        },
        "aborted": false,
        "timeoutCb": null,
        "upgradeOrConnect": false,
        "parser": null,
        "maxHeadersCount": null,
        "reusedSocket": false,
        "host": "akab-eo4izmhcazyzgoo3-uugtoalgbocarjuy.luna.akamaiapis.net",
        "protocol": "https:"
    },
    "data": "u001f�bu0000u0000u0000u0000u0000u0000u0000��os�Ɩ�����]�Vt}�u001fu0004�9�IM���N̹ٞs�u000b" ��D�u0010�9�Լ�۠DI�e���u0006@�7�=�82u0003Q䇫u001b����ߔŪx?��o������o�o�7�o&�������u001f�0J
}�[���������88S�T�U�/f����7cO���YW˯o���f5���u001fu000b�0��u000bGu001fCu001cF� ���o��l��B~Eu0014�0�E�'"Hr���Y��u0017��b�@u0004i$��=�-�3��_�e=����tV�7��ɏ_u0017������|i�e:���������o���^�?竳�_��MqqS�����͗��~뫻ǹ�c��,���7�z����u001fO������ȿ6�jy�����?�o�/U����z���:�y������MK�5��iU���{-��b~3�|}��~��ϳ�f&�fZ�u001e�����/Y?|���)u001f~R}����J>��?�<���W����o�OFQ�u001f����}q��~��Z���!���V�rV��������u001f������u000f���u001f����u00147��/������KA�ky�˯�UU������_�_~�u0004Ov��b�������>YO~�G��i������u0017�G)n�W�_;����|m�]/�^����rZ5�0�/���o޿��X����G4�)�z��ؾ��j�^NW_����u0017����Ͽ^_�̟�O~�/������?ͥmW��W�b&�u0013��������o�뷫�rz�nu001e�L���ߕU��0)f��-vY��������{m�L���(��l���z>u0017���sfu001eMu0001u0019�u0001�a#u0013u001du001eu0019)L0N�g�u0004��F"bSu0011�u0014��?��L�N'�y=��g7�Ye��g؄�br�+MEu0010Eu000f��,yn���i��Wu001f*u001du0019=R��?
}�u0001u000fvI��u001e);�#u0005Qp��)4{�o�)Ty(�u000f�t�����C��W�b>�̪շ�Bq�g��u000f�o��w���Xڹw*�Ma�G/~:�c�u0003?�_u0012�����z�u0011u0015~�t�����o�
}45u0006A8��
}De�y�������,z���i
]K#���og?`

**Comment by sena2112** [comment]
There is published bug, is it related on this?
https://github.com/axios/axios/issues/5296

**Comment by sena2112** [comment]
cc @bmatthew @ananner

**Comment by majakubiec** [comment]
Hi @sena2112,

Thanks for created issue. We are investigating it. I'll do my best to keep you up to date.

**Comment by sena2112** [comment]
Hi @majakubiec,
Could we conclude that it is due to axios 1.2.0 version?

**Comment by Slonimskaia** [comment]
Hi @sena2112,

This issue is under our investigation. We will give you any update as soon as possible.

Best regards,
Tatiana Slonimskaia

**Comment by lkowalsk-akamai-com** [comment]
Hi @sena2112, we've released today new version of Edgegrid-node with newer axios. Can you please check if you are still seeing this error?

**Comment by sena2112** [comment]
Hi @lkowalsk-akamai-com 
Thank you for updating. I cannot reproduce on this with new version. Then could we conclude it caused by axios?

**Comment by lkowalsk-akamai-com** [comment]
There were no other changes in the area and it indeed looked like the error in 1.2.0 version of axios. Please close the ticket unless you have any additional questions.
