### ISSUE TITLE
Request headers not used in request to OPEN API

### ISSUE THREAD

**Issue by iangetz** [akamai/AkamaiOPEN-edgegrid-node#139]
I have an existing node.js tool that pulls Property Manager information via PAPI. I don't like the "prp_", "ctr_", "grp_", etc. appended values so I have always used the PAPI-Use-Prefixes request header set to false.

When I upgraded from akamai-edgegrid@3.2.0 to akamai-edgegrid@3.4.0, Edgegrid appears to ignore the request header key/values in my code (i.e. {'PAPI-Use-Prefixes': false}) and the response includes the undesired "prp_", "ctr_", "grp_" appended values to the property ID, contract ID, and group ID. 

I'm able to resolve this problem by downgrading back to akamai-edgegrid@3.2.0 (no other code changes). 

Was the ability to set headers removed from v3.4.0? Thanks.

**Comment by dstopka** [comment]
Hi @iangetz!

We've investigated your issue. It seems to be a problem related to bumping the version of `axios`. Headers with value of `false` are being ignored. I can suggest using string explicitly instead of a boolean value with v3.4.0: `{'PAPI-Use-Prefixes': 'false'}`. Let me know if it helps!

Regards,
Darek

**Comment by iangetz** [comment]
Thank you, @dstopka! I kept my projects on v3.2.0. Is the use of a string ('false') just a temporary workaround until the next version or is that the approach going forward? Thanks, again.

**Comment by iangetz** [comment]
Ah. I understand. This bug is in a dependency. And it would not be recommended to override its behavior in case they fix it in the future. Thank you. This ticket can be closed.
