### ISSUE TITLE
DXE-3676 Axios closing the socket, resulting in a HTTP null response to client

### ISSUE THREAD

**Issue by akaganeshmurthy** [akamai/AkamaiOPEN-edgegrid-node#194]
Trying to use the edgegrid library for purge API calls, but getting the following error trace:
`{
    "level": "error",
    "message": "Internal API Error",
    "name": "AkamaiError",
    "service": "cdn-cache-purge",
    "awsRequestId": "1e846559-dfba-4e30-a9d2-9ef8894cb530",
    "errorId": "8122f00f-680e-4862-89a7-3da6203e7595",
    "stack": "AkamaiError: Internal API Error\n    at /var/task/common/src/common.js:56:13\n    at /opt/nodejs/node_modules/akamai-edgegrid/src/api.js:101:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "cause": {
        "message": "socket hang up",
        "name": "Error",
        "stack": "Error: socket hang up\n    at AxiosError.from (/opt/nodejs/node_modules/axios/dist/node/axios.cjs:837:14)\n    at ClientRequest.handleRequestError (/opt/nodejs/node_modules/axios/dist/node/axios.cjs:3083:25)\n    at ClientRequest.emit (node:events:517:28)\n    at TLSSocket.socketOnEnd (node:_http_client:525:9)\n    at TLSSocket.emit (node:events:529:35)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"`

The client making the request is an AWS lambda instance. Is this a known issue with Axios and proxies, or is this something coming from the client side? 
[new_error_line_101_feb_28.txt](https://github.com/akamai/AkamaiOPEN-edgegrid-node/files/14439445/new_error_line_101_feb_28.txt)

**Comment by ckulinsk** [comment]
Hi @akaganeshmurthy,

Thank you for raising this issue. We will get back to you after our investigation if this issue can be addressed.

Regards,
Cyryl

**Comment by mimazaka** [comment]
Hi @akaganeshmurthy,

Looking on error provided in logs attached to this ticket it seems like an issue on API level. I have contacted API team and was asked to provide answer for following questions:

```
Are you still facing this issue?
If so, how often does it happen?
Is it always/only for /tag?
Were you able to test with any other client? (postman for instance)
```
Please let me know if this is still valid issue and provide answers for these questions.

Regards,
Michał
