### ISSUE TITLE
Responses should always be json

### ISSUE THREAD

**Issue by AlbertBertilsson** [akamai/AkamaiOPEN-edgegrid-node#26]
We have noticed that when we get error responses they are in html format, this is a big problem. Ideally the library would only return json for easy parsing and error management. This also relates to the existing PR to improve the error handling.

**Comment by ktyacke** [comment]
Can you provide specific examples? The library itself isn't doing any conversion on the error messages, so if you are receiving HTML it would most likely be coming from the API you are calling. Are you able to confirm this?

**Comment by AlbertBertilsson** [comment]
We weren't expecting this so our logging only caught the first line:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

We changed our purging to only purge 300 items at a time instead of 500 at a time and the errors dissappeard. We might have exceeded the limitations, still the response should be some nice json.

**Comment by ktyacke** [comment]
Hey @AlbertBertilsson I agree with you wholeheartedly; unfortunately, the response data returned is not something that can be controlled by the signing library, but by the API itself. As such, I would suggest opening a post at https://community.akamai.com/community/developer and let them know the issues you're running into.

**Comment by stevemcginnis** [comment]
This is a message from http layer, not the akamai service. You should
always check http status codes first before accessing the message. You may
get http status codes from intermediate devices such as proxies, totally
beyond the control of the service developer. This is a general practice you
should always follow when accessing any api

**Comment by ktyacke** [comment]
Hey @stevemcginnis thanks for the insight, I wasn't aware of this personally. That being the case, I am more than happy to accept PR's to help resolve this issue! 

@AlbertBertilsson If you run into any further issues specific to purging, I would still recommend opening up a post on the community so you can get connected with some additional information.

Thanks to you both for pointing this out, and hoping to see a PR to help resolve this issue.

Cheers!

Kyle

**Comment by AlbertBertilsson** [comment]
We'll switch to the new version first and improve logging in our application. We are expecting to be very heavy users of this library and if we still have any issues we'll catch them. I think I have a good idea on how to reproduce it.

**Comment by ktyacke** [comment]
Sounds good @AlbertBertilsson If you do run into any issues or have other suggestions for improvements please don't hesitate to reach out, or better yet, open a PR.
