### ISSUE TITLE
Edge API does not handle 413 response code correctly and returns html instead of JSON

### ISSUE THREAD

**Issue by jimjaeger** [akamai/AkamaiOPEN-edgegrid-node#33]
I used the edge auth / send methods with the /ccu/v3/invalidate/url/ entrypoint and the server seems to return a statuscode 413 when the entitiy is too long. 

The send message does not handle this 413 status code and html response message. It returns the 413 html message instead of returning any json response.

Please address:
- Return JSON response in API and maybe in server response aswell for such conditions.
- Handle these status code with a error that the caller can react in a good case.

Thanks.

**Comment by lkowalsk-akamai-com** [comment]
Hi, additional header was added that should fix this issue.
