### ISSUE TITLE
README.md .edgerc example

### ISSUE THREAD

**Issue by dmcallis1** [akamai/AkamaiOPEN-edgegrid-node#46]
Reported by a customer:

The example '.edgerc' content 'host' attributes contains trailing forward slashes:

[default]
host = akaa-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.luna.akamaiapis.net/

The customer included these and subsequently encountered auth issues (signature does not match), due to the confusion.

Can this be removed? It doesn't conform to other .edgerc examples on other projects...

**Comment by piotrpio** [comment]
Hello @dmcallis1 
The issue with trailing slashes in `host` property has been fixed in version 3.0.5, so now it should not be failing if `host` ends with `/` (as presented in `README.md` example). Can you confirm it is working now?
Thanks
