### ISSUE TITLE
Escape unicode characters when body length > max body

### ISSUE THREAD

**Issue by TristanBaoui** [akamai/AkamaiOPEN-edgegrid-node#52]
While performing POST request body truncation if body length is larger than maximum 131072, if body contains unicode characters like emoji, API will return 401 status with 'Signature does not match' error.

Unicode characters should be escaped in order for the signature to match.
example: '🤖' => '\\uD83E\\uDD16'

**Comment by synedra** [comment]
Have you set max-body?

Kirsten
