### ISSUE TITLE
P0: Need support for POSTing binary body data

### ISSUE THREAD

**Issue by dctheobald** [akamai/AkamaiOPEN-edgegrid-node#54]
It doesn't appear that using edge.auth() / edge.send() you can upload binary data like a *.tgz tarball.  This is necessary to interact with the new EdgeWorkers OPEN API.  Can support or suggestions for existing usage if it exists, be provided for this use case?  Thanks!

**Comment by dctheobald** [comment]
After some trial and error debugging, I have discovered there are two places in this project where the request entity body is trying to be coerced into a JSON string and/or key/value form data when the body may not be those types.  If the following changes are made, binary data can be passed through successfully if sent as a Uint8Array type (eg: _new Uint8Array(fs.readFileSync(edgeworkerTarballPath, {encoding: null})_)

1) In /src/api.js, line 62 - need to add clause to if condition to preclude Uint8Array objects from being sent to JSON.stringify(), such as _if (typeof(req.body) === 'object' && !(req.body instanceof Uint8Array)) {...}_

2) In /src/helpers.js, line 29 - need to add clause to if condition to preclude Uint8Array objects from being transformed into form data key/value pairs, such as _if (typeof preparedBody === 'object' && !(request.body instanceof Uint8Array)) {...}_

**Comment by dshafik** [comment]
A better option here is to use a [stream](https://nodejs.org/api/stream.html), so that we don't have to read the data into memory unless required (e.g. for signing). Not doing this limits us to the 256MB max string limit, and has bitten us in the NetStorage library.

**Comment by dctheobald** [comment]
This issue can be closed as v3.0.8 of edgegrid ([PR](https://github.com/akamai/AkamaiOPEN-edgegrid-node/pull/57/files)) resolved my concerns.
