### ISSUE TITLE
Need option to rate-limit

### ISSUE THREAD

**Issue by david-prior** [akamai/AkamaiOPEN-edgegrid-node#56]
As API calls can be rate-limited, there should be an option within the edgegrid library to rate-limit.  Rate limiting could be applied elsewhere, but the most logical place would be in the edgegrid library

**Comment by majakubiec** [comment]
Hi @david-prior,

We lack requirements on how this could be implemented/ should work. If you have some ideas how it should work or would like to open a PR with this feature I'd be happy to review it :D.

Anyway It's an old issue so I will close it, but feel free to reopen it if you want to discuss it further.
