### ISSUE TITLE
Invalid timestamp

### ISSUE THREAD

**Issue by Carlwirkus** [akamai/AkamaiOPEN-edgegrid-node#62]
HI, I keep getting the following issue:

"type": "https://problems.purge.akamaiapis.net/-/pep-authn/request-error"
"title": "Bad request",
"status": 400,
"detail": "Invalid timestamp"

I've read it's to do with not syncing with NTP time. How would I do this with this node client?

**Comment by majakubiec** [comment]
Hi @Carlwirkus,

I am closing this issue as its been some time since it got created.

Feel free to reopen it if the issue persists.

BR
