### ISSUE TITLE
Requests that follow 30x redirects return unauthorized. 

### ISSUE THREAD

**Issue by cbarlow1993** [akamai/AkamaiOPEN-edgegrid-node#63]
## The Issue

Some of Akamai's documented APIs have optional parameters. Papi example in [docs](https://developer.akamai.com/api/core_features/property_manager/v1.html#getpropertyversionrules). 

> /papi/v1/properties/{propertyId}/versions/{propertyVersion}/rules{?contractId,groupId,validateRules,validateMode}

In this example, the contractId and groupId are optional. If these are not supplied and the API is called, I receive a 401. Tracing this through a proxy, what seems to happen is it's hitting one endpoint, receiving a 302 redirect to a URL which then contains generated contractId and groupId parameters and making another request. 
```
{
  "type": "https://problems.luna.akamaiapis.net/-/pep-authn/deny",
  "title": "Not authorized",
  "status": 401,
  "detail": "The signature does not match",
... 
}
```

If I make a request using the optional parameters already set, the request is successful and returns a 200 with the expected data. 

## The Bug
I believe the issue lies with the redirected request utilizing the same Auth token as the first request which is extremely time-sensitive and has expired, hence returns a 401 Not authorized error as below. 

This can also be seen using the POSTMAN API client.

**Comment by cbarlow1993** [comment]
After looking deeper into the code, I can see that it does recalculate the Auth headers so my suspicion here is invalid... the investigation continues...

**Comment by piotrpio** [comment]
Hello @cbarlow1993 
Thanks for submitting the issue. Can you tell me which version of edgegrid you are using? I tested 3.0.8 with the request you provided (fetching property version without `contractId` and `groupId`) and everything works fine (authorization header is recalculated)
