### ISSUE TITLE
Plan for alternative to request package?

### ISSUE THREAD

**Issue by siwinski** [akamai/AkamaiOPEN-edgegrid-node#64]
Given https://github.com/request/request/issues/3142 and the `request` module going into "maintenance mode", is there a plan for using an alternative package for this library?

**Comment by lucascaro** [comment]
![request_-_npm](https://user-images.githubusercontent.com/261395/99862563-0dde1100-2b4f-11eb-8127-46c5d3192cac.png)

**Comment by Sushmeet** [comment]
I would like to also request and ask the same question. For context we are getting security vulnerabilities errors with synk 
edgegrid@3.0.8 › request@2.88.0 › har-validator@5.1.3 › ajv@6.10.2

Both the request library and har-validator are deprecated. It would be great to know if this is something that is on the road map or if there is alternative for this. 

Thanks

**Comment by siwinski** [comment]
Ping.  I am getting worried that this library is not even supported anymore given that this issue has remained unanswered since it was submitted over a year, the last commit to this repo was in September 2019, and the last tagged release was in December 2016.

**Comment by piotrpio** [comment]
Hello @siwinski 
Thanks for submitting the issue. We are currently working on it a new version replacing `request` will be released soon. We are focused on getting rid of all known security vulnerabilities and updating dependencies.

**Comment by monwolf** [comment]
@piotrpio what it means soon? the module request was deprecated in the middle of 2019, after two years It's time to remove it, we can't deploy our developments to production cause we don't pass our security tests if we include edgegrid library.

**Comment by piotrpio** [comment]
@monwolf Sorry for any inconvenience caused. This work is in progress and we have the necessary fix ready, but currently we are having some issues in the overall process that blocks us with releasing it. We are working on making this release happen, but cannot share any timeliness at this point.

**Comment by lkowalsk-akamai-com** [comment]
We believe that with recent release this issue is resolved.
