### ISSUE TITLE
TypeScript-ize or add TypeScript declaration files?

### ISSUE THREAD

**Issue by siwinski** [akamai/AkamaiOPEN-edgegrid-node#71]
There are no types provided for using this library in a [TypeScript](https://www.typescriptlang.org/) project.  Would you be interested in either:
1) Converting this library to [TypeScript](https://www.typescriptlang.org/)?
2) Adding [TypeScript declaration files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) (i.e. `*.d.ts` files and a `types` property in `package.json`)?

If you are interested and/or not opposed, I am willing to start this work on my company's time and provide the work as a pull request to this repo.  If you are not interested and/or opposed, I will try to get the types added separately from this repo via [DefinitelyTyped](https://definitelytyped.org/).

**Comment by thomaswr** [comment]
@siwinski 
Do you have a rough timeline for this decision / the following solution?

**Comment by lkowalsk-akamai-com** [comment]
@thomaswr @siwinski 
Thank you for bringin this to our attention. We are verifying options and should get back with a decision within next week or two. Sorry for not responding to this ticket more promptly.

**Comment by dstopka** [comment]
Hi @siwinski @thomaswr,
We've decided to go with the second suggested option and we are working on adding TypeScript declaration files to this project. It'll be included in the future release.
I will close this issue now, but if you have any further questions feel free to reopen it.
Regards,
Darek

**Comment by maksym-opanasenko** [comment]
This is how it works, you pay 1000 pounds for using the CDN and then write the type definitions manually =(

**Comment by lkowalsk-akamai-com** [comment]
@thomaswr @siwinski This capabilites were just added with 3.2.0 release. Please check. I will close this ticket - feel free to reopen in case something is not working as expected.
