### ISSUE TITLE
Upgrading to akamai-edgegrid returning gibberish gzip response

### ISSUE THREAD

**Issue by swathimr** [akamai/AkamaiOPEN-edgegrid-node#83]
We are trying to update Akamai CLI Edgeworkers from `edgegrid` to `akamai-edgegrid`. However the gzip response with the edgegrid library was a "buffer" and with the akamai-edgegrid the response is some gibberish stream. Can you please let me know if we need to pass any header to receive the gzip response as buffer ? It is currently breaking our existing module. 

`"\\u001f�\\b\\u0000 xz^\\u0000\\u0003�X�n�6\\u0014V;\\f[}��f\\u001b�+�\\u0003*y�lɖZ#�\\u0012�Y��h��k�4\\r\\u0018�v�Ȓ+RM��\\u0017{�=��`�{�����\\u001d��-Ki��u��>�b�<?\\u001fy~x���A�;\\u001e��B\\u0003_Y\\f\\u0019�Ѵ,����0L\\u0004ߦY7�� �4�Yo֛V�2`�Z]AƂ��PD\\u0019\\u000e\\u0001\\n���_c\\u0007�R���]�\\u000f��H��(����o�GH\\u0012\\u001fS��S��Ox����\\u0017S����%�b����Ȱ\\\\��*ʗv0���\\bbp����o\\u0007��\\u000f\\u0004�\\u001f�(��S��\\u0011\\u000e��\\\\�(\\u000fv��vǬ[5�u�m=�\\u001aF��4H\\u000b7��YwC�\\u000fN:�n��}"`

**Comment by swathimr** [comment]
cc @bmatthew @ananner

**Comment by lkowalsk-akamai-com** [comment]
Hi @swathimr , this issue should be fixed now. Please verify if reopen in case any problems.
